### ISSUE TITLE
workflow steps hang

### ISSUE THREAD

**Issue by klmcadams** [ansys/pymechanical#460]
Frequently, the embedding tests will hang whenever the workflow is being run. We should add a time limit to the steps, and if the time limit is exceeded, run the step again automatically. We could limit each step to have a certain number of retries (maybe 2 retries max). This way, we won't have to manually cancel & re-run the steps that hang

or figure out why they hang, and see if we can fix the issue through the code

**Comment by RobPasMue** [comment]
I have the feeling that the "hanging" beahvior is due to the license server - i.e. the container is not able to retrieve the license somehow. The "run the step again" behavior is not available through GitHub Actions. You have to retrigger it either manually or through a different workflow. My suggestion would be to limit the parallelization to 1 embedding job at a time - if that makes sense or is not done yet. It might be best to investigate the actual reason that is causing it to fail...

**Comment by koubaa** [comment]
@RobPasMue I agree, this could be hiding a stability issue. Let's get to the bottom of it
